name: "Check if PR introduces errant RFC-2119"
on: 
  pull_request:
      types: [opened, edited]
      paths:
        - index.html

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v10
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: " must | must not | shall | shall not | should | should not | may"
